### ISSUE TITLE
Problem with actions argument of npc.add_schedule_entry method

### ISSUE THREAD

**Issue by BrunoMine** [hkzorman/advanced_npc#27]
I believe the syntax is not correct, or maybe the API uses the same term `actions` to refer to two different things.
https://github.com/hkzorman/advanced_npc/blob/175d07476daa5b217f9e32ee8837d315fc104feb/npc.lua#L945
1º case - `actions` is a [table with some action aguments](https://github.com/hkzorman/advanced_npc/blob/master/data/occupations/default_miner.lua#L19). In this case, the table must contain some values such as `min_count` and `max_count` for example.
2º case - `actions` is one of the [arguments of the first case](https://github.com/hkzorman/advanced_npc/blob/master/data/occupations/default_miner.lua#L26).

After all, what is the correct argument for [actions](https://github.com/hkzorman/advanced_npc/blob/175d07476daa5b217f9e32ee8837d315fc104feb/npc.lua#L945)? [actions](https://github.com/hkzorman/advanced_npc/blob/master/data/occupations/default_miner.lua#L19) or [actions](https://github.com/hkzorman/advanced_npc/blob/master/data/occupations/default_miner.lua#L26)?

**Comment by BrunoMine** [comment]
Maybe it's the first case
https://github.com/hkzorman/advanced_npc/blob/175d07476daa5b217f9e32ee8837d315fc104feb/npc.lua#L943

**Comment by hkzorman** [comment]
Yes @BrunoMine , actions in this case is the first link. You provide a Lua array which will be executed in order. This Lua array can contain:
* An action
* A task
* A property change (which is executed immediately and doesn't wait for the actions/tasks timer, please look at [this](https://github.com/hkzorman/advanced_npc/blob/175d07476daa5b217f9e32ee8837d315fc104feb/npc.lua#L1003))
* A schedule query/check (this is for advanced jobs which require constant looking around, like mining, farming, cutting trees, etc. and is still in progress. The [farmer occupation](https://github.com/hkzorman/advanced_npc/blob/master/data/occupations/default_farmer.lua) uses it)
