### ISSUE TITLE
How put a program in queue

### ISSUE THREAD

**Issue by BrunoMine** [hkzorman/advanced_npc#40]
And this way does not allow you to queue multiple programs, apparently it runs all at once.
```
npc.programs.execute(self, "advanced_npc:walk_to_pos", {
	end_pos = {
		place_type="bed_primary", 
		use_access_node=true
	}
})
npc.programs.execute(self, "advanced_npc:use_bed", {
	pos = "bed_primary",
	action = npc.programs.const.node_ops.beds.LAY
})
npc.programs.execute(self, "advanced_npc:idle", {
	acknowledge_nearby_objs = false,
	wander_chance = 0
})
```

**Comment by hkzorman** [comment]
Regarding your first comment: you can enqueue programs using:
`npc.exec.enqueue_program(self, program_name, arguments, interrupt_options)` where `arguments` and `interrupt_options` are tables.
Regarding second comment: that variable is now `self.npc_state.movement.is_laying`

**Comment by BrunoMine** [comment]
I would like to suggest you about `interrupt_options`. While this is important, we can make this less trivial for a first encodiing, even because this is irrelevant to some short programs.
If it is missing, it can cause crashes. Can you make this optional?

**Comment by hkzorman** [comment]
Pushed change to allow `nil` `interrupt_options` argument

**Comment by hkzorman** [comment]
Schedule query/check is not supported anymore. 
It can be easily implemented as a program which makes it more flexible... I have been thinking to actually implement it but not sure. 
What are your thoughts on this?

**Comment by BrunoMine** [comment]
Well, I think there must be a program that does this, eventually we will have one program (or a sequence of programs) within another.
Optionally it can run continuously while the queue is empty.
I currently use this to define interactions within a house, it's similar to a plantation, but every object in the house has a different interaction.

**Comment by hkzorman** [comment]
Ok, sounds good! I guess I will implement a `advanced_npc:node_query` which does this, and can be run as a state program (which means will be continously enqueued when queue is empty). I had been thinking on doing it but was not sure... will do it.

**Comment by BrunoMine** [comment]
Thanks, this is a very important tool to summarize a ton of codes.

**Comment by hkzorman** [comment]
I have started implementation of `node_query` program. There will be some changes. What used to be "actions" and "none_actions" will only support programs. So, for example, in the case of the farmer, instead of "actions" being:
  - Walk to pos
  - Stand
  - Dig
  - Stand

There will be a program that will execute these instructions.

**Comment by BrunoMine** [comment]
I look forward to start testing.

**Comment by BrunoMine** [comment]
Ok, I'll start testing and reporting errors found (and maybe a solution).
