### ISSUE TITLE
NPCs can not find objects on another floor of the house

### ISSUE THREAD

**Issue by BrunoMine** [hkzorman/advanced_npc#46]
They remain locked on the same floor in node_query check (This needs to be made clear in the documentation). This is pretty bad, but you can work around this problem by using programs that are conditioned to NPC locations. How is this possible?

**Comment by BrunoMine** [comment]
But you can also create different types of search.

**Comment by BrunoMine** [comment]
Yes, coincidentally, the NPC eventually found a box on the ground, but his own box was upstairs and he went up the stairs and through a door walking on the carpet of the house, that spatial recognition surprised me. But as this was a coincidence, he stays upstairs interacting with the same box until bedtime.

**Comment by BrunoMine** [comment]
I want to take this opportunity to inform you of a small inconvenience.
Sometimes he closes the door and crosses it, it seems to me that he does not understand which direction the door has been placed.

**Comment by hkzorman** [comment]
The pathfinder code is very good at moving through stairs, and I added the door support (at least for MTG default doors and `cottages` mod doors) and it works quite ok.

The problem with closing the door and then moving through it is a small bug in which the NPC thinks it has moved across the door and is completely at the other side, and then rotates back to look at the door to close it. Here is the problem, it has not moved completely across the door, and then it rotates and actually stays inside. I have noticed this and is in my to-do list.

However, the movement is anything but smooth, and NPCs look like they are teleporting when walking (which actually they do, they teleport as well). I have to find a better way to smooth out the movement.

**Comment by BrunoMine** [comment]
Yes, but the game is already very interesting with these beings living in a house. 
Maybe we can make ghosts to take advantage of this problem. :D

**Comment by hkzorman** [comment]
Yeah, that is a good idea! :D will look at expanding the radius.

**Comment by hkzorman** [comment]
I actually checked the code and the radius already is 3D (it is not flat).
So you can find other objects by expanding your radius. If your floor height is 3 blocks, you would have to make your radius 5:
[] <- actual node
------ <- second floor nodes
|
|
|

**Comment by BrunoMine** [comment]
If I expand the radius this does not solve because the height limit is 3 blocks.

[code in node query](https://github.com/hkzorman/advanced_npc/blob/commands_api/executable/programs/builtin/node_query.lua#L33)
[code in find_nodes function](https://github.com/hkzorman/advanced_npc/blob/commands_api/executable/locations.lua#L326)

**Comment by hkzorman** [comment]
You are completely right about this, missed that part. Pushed a fix for this: d16b5419a94ec993e93b7265868b73ba2ceff944

**Comment by hkzorman** [comment]
Regarding 
> Sometimes he closes the door and crosses it, it seems to me that he does not understand which direction the door has been placed.
Should be addressed and fixed by #51

**Comment by BrunoMine** [comment]
I believe this is much important because this textures can be completelly unseless in some situations.

**Comment by BrunoMine** [comment]
Fixed.
