### ISSUE TITLE
walk_to_pos does not walk to an exact position

### ISSUE THREAD

**Issue by BrunoMine** [hkzorman/advanced_npc#55]
`walk_to_pos` program does not walk to an exact position, even using the `optimize_one_node_distance=false` parameter.
This only happens when the NPC needs to go to the next coordinate. When that happens the NPC does not walk, it just rotates.
Branch [clean_api](https://github.com/hkzorman/advanced_npc/tree/clean_api)
Minetest [0.5.0-dev](https://github.com/minetest/minetest)
Mod test: [sociedades](https://github.com/BrunoMine/sociedades)
_In the picture, the NPC should be sideways, but it just rotated to interact._
![bug de rotacao](https://user-images.githubusercontent.com/7986261/40378435-ea96c53e-5dc9-11e8-8cb2-dd6e6842602c.png)

**Comment by hkzorman** [comment]
Latest push (660f00c17da5f76fa46abfd06180cb89e8069424) in branch `clean_api` is second attempt to fix this.
I wasn't able to test with `sociedades` but I saw noticeable improvement in the farmer NPC in `mg_villages_npc`. Please try and let me know.

If it doesn't work, I know what to do next.

**Comment by BrunoMine** [comment]
Sorry, I've been a little busy with another [mod](https://forum.minetest.net/viewtopic.php?f=9&t=20199&p=320010#p320010) that I'm preparing for my future server.
The problem was fixed. Thank you.
