### ISSUE TITLE
character model compatibility

### ISSUE THREAD

**Issue by BrunoMine** [hkzorman/advanced_npc#60]
I've noticed that the API applies settings in the `character.b3d` model to work with the model provided by the player_api mod (minetest.0.5.0). Is it possible to create a compatibility to work with minetest 0.4.16?

**Comment by hkzorman** [comment]
Not sure what are you talking about here. The `advanced_npc` API does nothing to `character.b3d`, except use it. The only thing I certainly do is set the collision box. Is this what you are referring to?

**Comment by BrunoMine** [comment]
probably yes. But if this is too complex you can ignore it.

**Comment by hkzorman** [comment]
I have been thinking I would like to support this as well, just not sure
how. Maybe the version number can help.

Also, I have removed the mob registration from the advanced_npc API. It is
up to mods now to register.

I may have an idea what to do, will let you know if it works.

**Comment by BrunoMine** [comment]
You can use the collision box set by mobs_redo.

**Comment by BrunoMine** [comment]
For example, my mod sets the collision box to be used in mobs_redo, your API should work based on [it](https://github.com/BrunoMine/sociedades/blob/master/sunos/npc/npc.lua#L410).

**Comment by BrunoMine** [comment]
If you do this, the responsibility for arranging the mesh and its operation will be from the mod that makes the registration.

**Comment by hkzorman** [comment]
I'm having a hard time finding what you would like me to change. As I said in first comment, the API doesn't registers an entity anymore.

The entity has to be registered by the implementing mod, and hence it has to set a collisionbox.

Is there any particular area of advanced_npc that you would like me to change that you can point out?

**Comment by BrunoMine** [comment]
OH, Sorry. This really is not related to your API.
